name: PR CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-and-build:
    name: Run tests and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test -- --runInBand
      - name: Build application
        run: CI=1 npm run build
      - name: Run freshness check
        run: npm run check:blueprint-progress-freshness
      - name: Check next-action deadlines
        run: npm run check:blueprint-next-actions
