export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    width: '100%',
    padding: '24px',
    boxSizing: 'border-box',
  },
  layout: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  columns: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  twoColumn: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 380px) minmax(0, 1fr)',
    gap: '24px',
  },
  card: {
    background: 'rgba(12, 16, 24, 0.65)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '16px',
    padding: '20px',
    backdropFilter: 'blur(14px)',
    boxShadow: '0 24px 48px rgba(0, 0, 0, 0.25)',
    color: '#f8fbff',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: 600,
    marginBottom: '12px',
  },
  modeTabs: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  modeButton: {
    borderRadius: '999px',
    border: '1px solid rgba(255, 255, 255, 0.18)',
    background: 'rgba(255, 255, 255, 0.08)',
    color: '#f8fbff',
    padding: '8px 16px',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'background 0.2s ease, border-color 0.2s ease',
  },
  modeButtonActive: {
    background: 'rgba(102, 178, 255, 0.28)',
    borderColor: 'rgba(120, 190, 255, 0.9)',
    color: '#fff',
  },
  modeButtonDisabled: {
    opacity: 0.5,
    cursor: 'default',
  },
  roomList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    maxHeight: '420px',
    overflowY: 'auto',
    paddingRight: '8px',
  },
  roomRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: '12px',
    padding: '12px 16px',
    background: 'rgba(18, 22, 30, 0.72)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    cursor: 'pointer',
    transition: 'transform 0.15s ease, background 0.2s ease',
  },
  roomRowActive: {
    background: 'rgba(96, 158, 255, 0.22)',
    borderColor: 'rgba(140, 190, 255, 0.6)',
  },
  roomRowMeta: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  roomRowTitle: {
    fontSize: '16px',
    fontWeight: 600,
  },
  roomRowSubtitle: {
    fontSize: '13px',
    color: 'rgba(224, 232, 255, 0.72)',
  },
  occupancyBadge: {
    fontSize: '12px',
    fontWeight: 600,
    padding: '4px 10px',
    borderRadius: '999px',
    background: 'rgba(80, 120, 255, 0.22)',
    color: '#dbe6ff',
  },
  detailCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  detailHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  detailTitle: {
    fontSize: '20px',
    fontWeight: 700,
  },
  detailSubtitle: {
    fontSize: '14px',
    color: 'rgba(224, 232, 255, 0.72)',
  },
  detailMetaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    alignItems: 'center',
  },
  detailBadge: {
    fontSize: '12px',
    padding: '4px 10px',
    borderRadius: '999px',
    background: 'rgba(20, 26, 38, 0.8)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    color: '#d5e4ff',
  },
  slotGrid: {
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
  },
  slotCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '14px',
    borderRadius: '12px',
    background: 'rgba(18, 24, 36, 0.78)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
  },
  slotRole: {
    fontSize: '14px',
    fontWeight: 600,
  },
  slotHero: {
    fontSize: '13px',
    color: '#e7f0ff',
  },
  slotPlaceholder: {
    fontSize: '13px',
    color: 'rgba(210, 220, 255, 0.65)',
  },
  slotActions: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  primaryButton: {
    borderRadius: '10px',
    border: '1px solid rgba(120, 190, 255, 0.9)',
    background: 'rgba(70, 140, 255, 0.35)',
    color: '#fff',
    fontSize: '13px',
    fontWeight: 600,
    padding: '8px 12px',
    cursor: 'pointer',
  },
  secondaryButton: {
    borderRadius: '10px',
    border: '1px solid rgba(255, 255, 255, 0.16)',
    background: 'rgba(255, 255, 255, 0.08)',
    color: '#fff',
    fontSize: '13px',
    fontWeight: 500,
    padding: '8px 12px',
    cursor: 'pointer',
  },
  dangerButton: {
    borderRadius: '10px',
    border: '1px solid rgba(255, 120, 120, 0.4)',
    background: 'rgba(255, 80, 80, 0.18)',
    color: '#ffe6e6',
    fontSize: '13px',
    fontWeight: 600,
    padding: '8px 12px',
    cursor: 'pointer',
  },
  buttonDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
  createForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  formRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    fontSize: '13px',
    color: 'rgba(220, 230, 255, 0.75)',
  },
  select: {
    borderRadius: '10px',
    border: '1px solid rgba(255, 255, 255, 0.18)',
    padding: '8px 12px',
    background: 'rgba(18, 24, 36, 0.9)',
    color: '#fff',
    fontSize: '14px',
  },
  input: {
    borderRadius: '10px',
    border: '1px solid rgba(255, 255, 255, 0.18)',
    padding: '8px 12px',
    background: 'rgba(18, 24, 36, 0.9)',
    color: '#fff',
    fontSize: '14px',
  },
  helperText: {
    fontSize: '12px',
    color: 'rgba(214, 226, 255, 0.72)',
  },
  errorText: {
    fontSize: '13px',
    color: '#ff9090',
  },
  placeholder: {
    padding: '36px',
    textAlign: 'center',
    color: 'rgba(224, 232, 255, 0.65)',
  },
  joinCodeRow: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  badgeList: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
}

