const baseBackground = 'linear-gradient(180deg, #020614 0%, #071227 50%, #010615 100%)'
const cardShadow = '0 32px 80px -64px rgba(12, 18, 38, 0.9)'

const styles = {
  page: {
    minHeight: '100vh',
    width: '100%',
    background: baseBackground,
    color: '#e2e8f0',
    display: 'flex',
    justifyContent: 'center',
    padding: '32px 16px 56px',
    boxSizing: 'border-box',
  },
  wrapper: {
    width: '100%',
    maxWidth: 560,
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  topBar: {
    borderRadius: 18,
    padding: '12px 18px',
    background: 'linear-gradient(135deg, rgba(18,31,64,0.92), rgba(8,13,30,0.95))',
    border: '1px solid rgba(94, 116, 255, 0.32)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  brandGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  brandMark: {
    fontSize: 16,
    fontWeight: 800,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: '#facc15',
  },
  brandTagline: {
    margin: 0,
    fontSize: 12,
    color: '#cbd5f5',
    letterSpacing: '0.03em',
  },
  profileAction: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeCard: {
    borderRadius: 22,
    padding: '22px 20px',
    border: '1px solid rgba(96, 165, 250, 0.35)',
    background: 'linear-gradient(175deg, rgba(37, 99, 235, 0.4) 0%, rgba(12, 18, 38, 0.92) 100%)',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    boxShadow: cardShadow,
  },
  noticeHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  noticeBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4px 12px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: '#e0f2fe',
    background: 'rgba(59, 130, 246, 0.35)',
  },
  noticeActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  noticeRefresh: {
    padding: '4px 12px',
    borderRadius: 999,
    border: '1px solid rgba(147, 197, 253, 0.45)',
    background: 'rgba(30, 58, 138, 0.55)',
    color: '#bfdbfe',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    cursor: 'pointer',
  },
  noticeToggle: {
    padding: '4px 10px',
    borderRadius: 999,
    border: '1px solid rgba(191, 219, 254, 0.28)',
    background: 'rgba(12, 23, 58, 0.6)',
    color: '#dbeafe',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    cursor: 'pointer',
  },
  noticeButtonDisabled: {
    opacity: 0.55,
    cursor: 'not-allowed',
  },
  noticeBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  noticeHeading: {
    margin: 0,
    fontSize: 20,
    fontWeight: 800,
    color: '#f8fafc',
    letterSpacing: '-0.01em',
  },
  noticeTimestamp: {
    fontSize: 12,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'rgba(222, 239, 255, 0.7)',
  },
  noticeCopy: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.6,
    color: '#dbeafe',
  },
  noticeList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  noticeListItem: {
    borderRadius: 16,
    border: '1px solid rgba(147, 197, 253, 0.2)',
    background: 'rgba(15, 23, 42, 0.72)',
    padding: '12px 14px',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  noticeListHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  noticeListTitle: {
    margin: 0,
    fontSize: 14,
    fontWeight: 600,
    color: '#f8fafc',
  },
  noticeListTimestamp: {
    fontSize: 11,
    color: 'rgba(191, 219, 254, 0.7)',
    letterSpacing: '0.05em',
  },
  noticeListCopy: {
    margin: 0,
    fontSize: 13,
    lineHeight: 1.5,
    color: 'rgba(221, 232, 255, 0.85)',
  },
  calloutCard: {
    borderRadius: 24,
    padding: '26px 24px',
    background: 'linear-gradient(170deg, rgba(15,23,42,0.88) 0%, rgba(2,6,23,0.92) 100%)',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    boxShadow: cardShadow,
    border: '1px solid rgba(30,41,59,0.55)',
  },
  calloutTitle: {
    margin: 0,
    fontSize: 24,
    fontWeight: 800,
    letterSpacing: '-0.01em',
    color: '#f8fafc',
  },
  calloutSubtitle: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.6,
    color: '#cbd5f5',
  },
  heroSection: {
    borderRadius: 26,
    padding: '24px 22px 30px',
    background: 'rgba(5, 10, 25, 0.92)',
    border: '1px solid rgba(30,41,59,0.55)',
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
    boxShadow: cardShadow,
  },
  heroHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  heroTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: '-0.01em',
  },
  heroCount: {
    fontSize: 12,
    fontWeight: 600,
    color: '#94a3b8',
  },
  heroList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  heroButton: {
    border: 'none',
    padding: 0,
    background: 'transparent',
    textAlign: 'left',
    cursor: 'pointer',
    borderRadius: 24,
    overflow: 'hidden',
    position: 'relative',
    transition: 'transform 0.22s ease, box-shadow 0.22s ease',
    boxShadow: '0 30px 70px -58px rgba(59,130,246,0.75)',
    aspectRatio: '2 / 1',
  },
  heroButtonContent: {
    position: 'relative',
    width: '100%',
    height: '100%',
    borderRadius: 24,
    overflow: 'hidden',
    border: '1px solid rgba(148,163,184,0.25)',
    background: 'rgba(15,23,42,0.6)',
  },
  heroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
    transform: 'scale(1.01)',
    transition: 'transform 0.3s ease',
  },
  heroFallback: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 32,
    fontWeight: 800,
    background: 'linear-gradient(135deg, rgba(59,130,246,0.35) 0%, rgba(30,41,59,0.85) 100%)',
    color: '#f8fafc',
  },
  heroNameOverlay: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    padding: '18px 22px',
    background: 'linear-gradient(180deg, rgba(2,6,23,0) 0%, rgba(2,6,23,0.85) 100%)',
    boxSizing: 'border-box',
  },
  heroName: {
    margin: 0,
    fontSize: 20,
    fontWeight: 800,
    letterSpacing: '-0.02em',
    color: '#f8fafc',
  },
  createCard: {
    border: '1px dashed rgba(148,163,184,0.45)',
    borderRadius: 20,
    background: 'rgba(15,23,42,0.5)',
    color: '#bae6fd',
    fontWeight: 700,
    fontSize: 15,
    minHeight: 96,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'border-color 0.2s ease, color 0.2s ease',
    width: '100%',
  },
  statusBox: {
    borderRadius: 20,
    border: '1px solid rgba(148,163,184,0.3)',
    background: 'rgba(15,23,42,0.62)',
    padding: '28px 22px',
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 1.7,
    color: '#cbd5f5',
  },
  retryButton: {
    marginTop: 16,
    padding: '10px 20px',
    borderRadius: 999,
    border: '1px solid rgba(59,130,246,0.6)',
    background: 'rgba(8,47,73,0.65)',
    color: '#e0f2fe',
    fontWeight: 600,
    cursor: 'pointer',
  },
}

export default styles
