export const styles = {
  root: {
    background: '#ffffff',
    borderRadius: 24,
    boxShadow: '0 28px 60px -46px rgba(15, 23, 42, 0.55)',
    padding: 18,
    display: 'grid',
    gap: 14,
  },
  searchColumn: {
    display: 'grid',
    gap: 10,
  },
  searchInputs: {
    display: 'grid',
    gridTemplateColumns: '1fr 120px',
    gap: 10,
  },
  searchInput: {
    padding: '12px 14px',
    borderRadius: 12,
    border: '1px solid #e2e8f0',
  },
  sortSelect: {
    padding: '12px 14px',
    borderRadius: 12,
    border: '1px solid #e2e8f0',
  },
  listBox: {
    border: '1px solid #e5e7eb',
    borderRadius: 16,
    padding: 12,
    maxHeight: '45vh',
    overflowY: 'auto',
    WebkitOverflowScrolling: 'touch',
    display: 'grid',
    gap: 10,
  },
  emptyState: {
    padding: 12,
    textAlign: 'center',
    color: '#64748b',
  },
  gameRow: {
    textAlign: 'left',
    display: 'grid',
    gridTemplateColumns: '64px 1fr auto',
    gap: 12,
    alignItems: 'center',
    padding: '10px 12px',
    borderRadius: 16,
  },
  gameRowActive: {
    border: '2px solid #2563eb',
    background: 'rgba(37, 99, 235, 0.08)',
  },
  gameRowInactive: {
    border: '1px solid #e2e8f0',
    background: '#f9fafb',
  },
  gameThumb: {
    width: 64,
    height: 64,
    borderRadius: 14,
    overflow: 'hidden',
    background: '#e2e8f0',
  },
  gameThumbImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  gameInfo: {
    display: 'grid',
    gap: 4,
  },
  gameTitle: {
    fontSize: 15,
    color: '#0f172a',
  },
  gameDesc: {
    fontSize: 12,
    color: '#64748b',
    lineHeight: 1.4,
  },
  gameMeta: {
    display: 'flex',
    gap: 12,
    fontSize: 12,
    color: '#94a3b8',
  },
  gameTags: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
    fontSize: 11,
    color: '#1d4ed8',
  },
  gameTagChip: {
    background: 'rgba(37, 99, 235, 0.12)',
    borderRadius: 999,
    padding: '3px 8px',
  },
  gameDate: {
    fontSize: 12,
    color: '#94a3b8',
  },
  detailBox: {
    border: '1px solid #e2e8f0',
    borderRadius: 20,
    padding: 16,
    display: 'grid',
    gap: 14,
    background: '#f9fafc',
  },
  detailPlaceholder: {
    border: '1px dashed #cbd5f5',
    borderRadius: 18,
    padding: 24,
    textAlign: 'center',
    color: '#64748b',
    background: '#fff',
  },
  conflictBox: {
    border: '1px solid rgba(248, 113, 113, 0.35)',
    borderRadius: 20,
    padding: 20,
    background: '#fff7f7',
    color: '#7f1d1d',
    display: 'grid',
    gap: 14,
  },
  conflictCard: {
    display: 'grid',
    gap: 12,
  },
  conflictTitle: {
    fontSize: 18,
    fontWeight: 700,
  },
  conflictBody: {
    margin: 0,
    fontSize: 13,
    lineHeight: 1.6,
  },
  conflictList: {
    display: 'grid',
    gap: 8,
  },
  conflictListItem: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 8,
    padding: '8px 12px',
    borderRadius: 12,
    background: 'rgba(248, 113, 113, 0.12)',
    color: '#991b1b',
  },
  conflictHero: {
    fontWeight: 700,
    fontSize: 14,
  },
  conflictRole: {
    fontSize: 12,
    color: '#b91c1c',
  },
  conflictHint: {
    margin: 0,
    fontSize: 12,
    color: '#b91c1c',
  },
  detailHeader: {
    display: 'grid',
    gap: 6,
  },
  detailTitle: {
    fontSize: 18,
    color: '#0f172a',
  },
  detailDesc: {
    margin: 0,
    fontSize: 13,
    color: '#475569',
    lineHeight: 1.6,
  },
  detailMeta: {
    display: 'flex',
    gap: 12,
    fontSize: 12,
    color: '#64748b',
    flexWrap: 'wrap',
  },
  detailLoading: {
    padding: 12,
    borderRadius: 14,
    background: '#fff',
    border: '1px solid #e2e8f0',
    color: '#475569',
    fontSize: 13,
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: '#0f172a',
  },
  refreshButton: {
    padding: '6px 12px',
    borderRadius: 12,
    border: '1px solid #2563eb',
    background: '#eff6ff',
    color: '#1d4ed8',
    fontWeight: 600,
    cursor: 'pointer',
  },
  tagSection: {
    display: 'grid',
    gap: 10,
  },
  tagList: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
  tagEmpty: {
    fontSize: 12,
    color: '#64748b',
  },
  tagChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 12px',
    borderRadius: 999,
    background: '#dbeafe',
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: 600,
  },
  tagRemove: {
    border: 'none',
    background: 'transparent',
    color: '#1d4ed8',
    cursor: 'pointer',
    fontSize: 12,
  },
  tagInputRow: {
    display: 'flex',
    gap: 8,
  },
  tagInput: {
    flex: 1,
    borderRadius: 12,
    border: '1px solid #cbd5f5',
    padding: '10px 12px',
    fontSize: 13,
  },
  tagSubmit: {
    padding: '10px 16px',
    borderRadius: 12,
    border: '1px solid #2563eb',
    background: '#2563eb',
    color: '#fff',
    fontWeight: 600,
    cursor: 'pointer',
  },
  ownerControls: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
  },
  ownerButton: {
    padding: '8px 14px',
    borderRadius: 12,
    border: '1px solid #1d4ed8',
    background: '#eff6ff',
    color: '#1d4ed8',
    fontWeight: 600,
    cursor: 'pointer',
  },
  ownerButtonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  dangerButton: {
    borderColor: '#dc2626',
    background: '#fee2e2',
    color: '#b91c1c',
  },
  statsSection: {
    display: 'grid',
    gap: 10,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
    gap: 10,
  },
  statCard: {
    background: '#fff',
    borderRadius: 14,
    border: '1px solid #e2e8f0',
    padding: 12,
    display: 'grid',
    gap: 4,
    textAlign: 'center',
  },
  statValue: {
    fontSize: 18,
    fontWeight: 700,
    color: '#1d4ed8',
  },
  statLabel: {
    fontSize: 12,
    color: '#475569',
  },
  topPlayerList: {
    display: 'grid',
    gap: 6,
    borderRadius: 12,
    background: '#fff',
    border: '1px solid #e2e8f0',
    padding: 12,
    fontSize: 13,
    color: '#475569',
  },
  topPlayerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  roleSection: {
    display: 'grid',
    gap: 10,
  },
  roleLabel: {
    fontWeight: 600,
    color: '#0f172a',
  },
  roleGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))',
    gap: 10,
  },
  roleButton: {
    borderRadius: 14,
    padding: '12px 14px',
    border: '1px solid #e2e8f0',
    display: 'grid',
    gap: 6,
    background: '#fff',
  },
  roleButtonActive: {
    borderColor: '#2563eb',
    background: 'rgba(37, 99, 235, 0.1)',
  },
  roleButtonInactive: {},
  roleButtonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  roleBadgeFull: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    padding: '4px 8px',
    fontSize: 11,
    fontWeight: 600,
    color: '#b91c1c',
    background: '#fee2e2',
    borderRadius: 999,
  },
  roleSlotMeta: {
    fontSize: 12,
    color: '#64748b',
  },
  joinControls: {
    display: 'grid',
    gap: 8,
  },
  joinButton: {
    padding: '12px 18px',
    borderRadius: 14,
    border: 'none',
    background: 'linear-gradient(135deg, #2563eb 0%, #3b82f6 100%)',
    color: '#fff',
    fontWeight: 700,
    fontSize: 15,
    cursor: 'pointer',
    boxShadow: '0 18px 40px -28px rgba(37, 99, 235, 0.85)',
  },
  joinButtonDisabled: {
    opacity: 0.45,
    cursor: 'not-allowed',
    boxShadow: 'none',
  },
  joinNotice: {
    fontSize: 12,
    color: '#b91c1c',
  },
  participantSection: {
    display: 'grid',
    gap: 10,
  },
  participantLabel: {
    fontWeight: 600,
    color: '#0f172a',
  },
  participantList: {
    border: '1px solid #e2e8f0',
    borderRadius: 16,
    padding: 12,
    display: 'grid',
    gap: 10,
    background: '#fff',
  },
  participantRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 13,
    color: '#1f2937',
  },
  participantName: {
    fontWeight: 600,
  },
  participantRole: {
    color: '#64748b',
  },
  seasonSection: {
    display: 'grid',
    gap: 10,
  },
  seasonCard: {
    background: '#fff',
    borderRadius: 16,
    border: '1px solid #e2e8f0',
    padding: 14,
    display: 'grid',
    gap: 8,
  },
  seasonHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontWeight: 700,
    color: '#0f172a',
  },
  seasonMetaRow: {
    fontSize: 12,
    color: '#475569',
    display: 'flex',
    gap: 12,
    flexWrap: 'wrap',
  },
  seasonActions: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  seasonArchive: {
    display: 'grid',
    gap: 10,
  },
  logSection: {
    display: 'grid',
    gap: 10,
  },
  logList: {
    display: 'grid',
    gap: 10,
  },
  logItem: {
    background: '#fff',
    borderRadius: 14,
    border: '1px solid #e2e8f0',
    padding: 14,
    display: 'grid',
    gap: 6,
  },
  logMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 12,
    color: '#64748b',
    gap: 12,
    flexWrap: 'wrap',
  },
  logText: {
    margin: 0,
    fontSize: 13,
    color: '#0f172a',
    lineHeight: 1.5,
  },
  enterButton: {
    marginTop: 4,
    padding: '12px 16px',
    borderRadius: 12,
    background: '#2563eb',
    color: '#fff',
    fontWeight: 700,
    border: 'none',
    cursor: 'pointer',
  },
}

export default styles
