// Capability-oriented runtime contracts
// Each capability describes: purpose, required files/hooks, optional adapters, and reference links.

export const CapabilityContracts = [
  {
    id: 'core.graph',
    label: 'Prompt Graph Core',
    purpose: 'Define game flow as nodes and edges.',
    files: ['/graph/prompt-graph.json'],
    hooks: [],
    adapters: [],
    references: [
      { title: 'State machines (machina)', href: '/api/refroot/machina.js-master/machina.js-master/README.md' },
      { title: 'javascript-state-machine', href: '/api/refroot/javascript-state-machine-master%20(2)/javascript-state-machine-master/README.md' },
    ],
  },
  {
    id: 'core.hooks',
    label: 'Hook Runtime',
    purpose: 'Inject logic via exported functions from /game/hooks/automation.js.',
    files: ['/game/hooks/automation.js'],
    hooks: ['transformPrompt', 'onUserAction', 'selectNext'],
    adapters: [],
    references: [],
  },
  {
    id: 'core.runtimeConfig',
    label: 'Runtime Config',
    purpose: 'Entry node, roles, timers, and mode flags.',
    files: ['/game/runtime.config.json'],
    hooks: [],
    adapters: [],
    references: [],
  },
  {
    id: 'ui.text',
    label: 'Text UI',
    purpose: 'Render prompts and choices as text; map user input to actions.',
    files: [],
    hooks: ['transformPrompt', 'onUserAction', 'selectNext'],
    adapters: [],
    references: [
      { title: 'ROT.js (for roguelike text UIs)', href: '/api/refroot/rot.js-master/README.md' },
    ],
  },
  {
    id: 'ui.canvas2d',
    label: 'Canvas 2D UI',
    purpose: 'Draw simple scenes/tiles on <canvas> 2D.',
    files: ['/game/pages/ui/main.json?optional'],
    hooks: ['onUserAction'],
    adapters: ['renderer.canvas2d'],
    references: [
      { title: 'PixiJS', href: '/api/refroot/pixijs-dev/README.md' },
    ],
  },
  {
    id: 'ui.webgl3d',
    label: 'WebGL 3D UI',
    purpose: 'Render 3D scenes and camera control.',
    files: ['/game/pages/ui/main.json?optional'],
    hooks: ['onUserAction'],
    adapters: ['renderer.webgl'],
    references: [ { title: 'Three.js', href: '/api/refroot/three.js-dev/README.md' } ],
  },
  {
    id: 'input.keyboard',
    label: 'Keyboard Input',
    purpose: 'Map keyboard events into user actions.',
    files: [],
    hooks: ['onUserAction'],
    adapters: ['input.keyboard'],
    references: [ { title: 'kibo-keyboard', href: '/api/refroot/kibo-keyboard-master/README.md' } ],
  },
  {
    id: 'input.gamepad',
    label: 'Gamepad Input',
    purpose: 'Map gamepad to actions or keyboard.',
    files: [],
    hooks: ['onUserAction'],
    adapters: ['input.gamepad'],
    references: [ { title: 'gamepad-to-keyboard-mapper', href: '/api/refroot/gamepad-to-keyboard-mapper-master/README.md' } ],
  },
  {
    id: 'grid.tilemap',
    label: 'Tilemap/Grid',
    purpose: 'Grid logic and tile-based movement.',
    files: [],
    hooks: ['onUserAction', 'selectNext'],
    adapters: [],
    references: [ { title: 'easystar.js', href: '/api/refroot/easystarjs-master/README.md' } ],
  },
  {
    id: 'ai.pathfinding',
    label: 'Pathfinding',
    purpose: 'Find routes on grid or navmesh.',
    files: [],
    hooks: ['onUserAction'],
    adapters: [],
    references: [ { title: 'yuka', href: '/api/refroot/yuka-master/README.md' } ],
  },
  {
    id: 'physics.basic',
    label: 'Basic Physics',
    purpose: 'Collision and gravity support via renderer adapter.',
    files: ['/game/pages/ui/main.json?optional'],
    hooks: ['onUserAction'],
    adapters: ['renderer.canvas2d|webgl+physics'],
    references: [ { title: 'Phaser', href: '/api/refroot/phaser-master/README.md' } ],
  },
  {
    id: 'network.socketio',
    label: 'Networking (Socket.IO)',
    purpose: 'Rooms, events, real-time messaging.',
    files: [],
    hooks: ['onUserAction'],
    adapters: ['net.socketio'],
    references: [ { title: 'socket.io', href: '/api/refroot/socket.io-main/README.md' } ],
  },
  {
    id: 'network.colyseus',
    label: 'Networking (Colyseus)',
    purpose: 'Authoritative rooms/patches.',
    files: [],
    hooks: ['onUserAction'],
    adapters: ['net.colyseus'],
    references: [ { title: 'colyseus', href: '/api/refroot/colyseus-master/README.md' } ],
  },
  {
    id: 'crdt.yjs',
    label: 'CRDT Sync (Yjs)',
    purpose: 'Shared state and presence.',
    files: [],
    hooks: ['onUserAction'],
    adapters: ['sync.yjs'],
    references: [ { title: 'yjs', href: '/api/refroot/yjs-main/README.md' } ],
  },
  {
    id: 'worker.offthread',
    label: 'Worker Off-thread',
    purpose: 'Move heavy compute to Worker with RPC.',
    files: [],
    hooks: ['onUserAction'],
    adapters: ['worker.rpc'],
    references: [
      { title: 'worker-rpc', href: '/api/refroot/worker-rpc-master/README.md' },
      { title: 'webcontainer-core', href: '/api/refroot/webcontainer-core-main/README.md' },
    ],
  },
  {
    id: 'timing.turns',
    label: 'Turns/Timeouts',
    purpose: 'Turn durations, step timers, auto-advance.',
    files: ['/game/runtime.config.json'],
    hooks: ['selectNext'],
    adapters: [],
    references: [],
  },
  {
    id: 'storage.snapshot',
    label: 'Snapshot/Save',
    purpose: 'Persist variables/history per set.',
    files: [],
    hooks: [],
    adapters: ['storage.snapshot'],
    references: [],
  },
];

