
---
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-match-sa
  annotations:
    iam.gke.io/gcp-service-account: $GCP_SA_FOR_METRICS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-match-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-match-deployment
  template:
    metadata:
      labels:
        app: open-match-deployment
    spec:
      serviceAccountName: open-match-sa
      containers:
        - image: us-docker.pkg.dev/open-match-public-images/open-match2/om-core
          imagePullPolicy: Always
          name: om-core
          ports:
          - containerPort: 8080
          env:
          - name: OM_LOGGING_LEVEL
            value: info
          - name: OM_REDIS_WRITE_HOST
            value: redis.default.svc.cluster.local
          - name: OM_REDIS_READ_HOST
            value: redis.default.svc.cluster.local
          - name: OM_OTEL_SIDECAR
            value: "true"
          
        # Add OpenTelemetry Collector sidecar
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          ports:
            - containerPort: 4317  # OTLP gRPC receiver
            - containerPort: 4318  # OTLP HTTP receiver
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otelcol-contrib/config.yaml
              subPath: config.yaml
      
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
---
# ConfigMap for OpenTelemetry Collector configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_max_size: 200
        send_batch_size: 200
        timeout: 5s

      memory_limiter:
        check_interval: 1s
        limit_percentage: 65
        spike_limit_percentage: 20

      resource:
        attributes:
          - key: k8s.cluster.name
            value: yi-standard-cluster
            action: insert
          - key: k8s.namespace.name
            value: default
            action: insert
          - key: k8s.pod.name
            from_attribute: k8s.pod.name
            action: upsert
          - key: service.name
            value: open-match-service
            action: insert

    exporters:
      googlemanagedprometheus:
        project: peteryizhong-gke-dev

    extensions:
      health_check:

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch, memory_limiter, resource]
          exporters: [googlemanagedprometheus]
---
apiVersion: v1
kind: Service
metadata:
  name: open-match-service
  labels:
    run: open-match-service
spec:
  ports:
    - port: 50504
      targetPort: 8080
      protocol: TCP
  selector:
    app: open-match-deployment
  type: LoadBalancer