name: Apply SQL migration (manual)

on:
  workflow_dispatch:

jobs:
  apply-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Apply SQL migration
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -e
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "ERROR: SUPABASE_DB_URL secret is not set" >&2
            exit 1
          fi
          psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f docs/sql/20251025_add_recompute_queue.sql
