name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ai-roomchat/starbase/ai-roomchat

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ai-roomchat/starbase/ai-roomchat/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build application
        run: npm run build
        env:
          CI: true

      - name: Start development server
        run: |
          npm run dev &
          echo $! > .dev-server.pid
        env:
          NODE_ENV: production

      - name: Wait for server to be ready
        run: |
          npx wait-on http://localhost:3000 --timeout 60000 || (cat .next/build-manifest.json && exit 1)

      - name: Run Playwright tests
        run: npx playwright test
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3000

      - name: Stop development server
        if: always()
        run: |
          if [ -f .dev-server.pid ]; then
            kill $(cat .dev-server.pid) || true
          fi

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ai-roomchat/starbase/ai-roomchat/playwright-report/
          retention-days: 30

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ai-roomchat/starbase/ai-roomchat/test-results/
          retention-days: 30
